<?php 
/**
 * views template to output one 'row' of a view.
 * This code was generated by the views theming wizard
 * Date: Sun, 2007-02-11 12:11
 * View: News
 *
 * Variables available:
 * $view -- the entire view object. Important parts of this object are
 *   News, .
 * $view_type -- The type of the view. Probably 'page' or 'block' but could
 *   also be 'embed' or other string passed in from a custom view creator.
 * $node -- the raw data. This is not a real node object, but will contain
 *   the nid as well as other support fields that might be necessary.
 * $count -- the current row in the view (not TOTAL but for this page) starting
 *   from 0.
 * $stripe -- 'odd' or 'even', alternating.
 * $created -- Display the post time of the node.
 * $created_label -- The assigned label for $created
 * $title -- Display the title of the node.
 * $title_label -- The assigned label for $title
 * $field_image_fid -- 
 * $field_image_fid_label -- The assigned label for $field_image_fid
 * $field_body_value -- 
 * $field_body_value_label -- The assigned label for $field_body_value
 *
 * This function goes in your views-list-News.tpl.php file
 */
  ?>
 <?php 
 switch ($view_type) {
	/*****************************************
	 * PAGE VIEW 
	 *****************************************/
 	case 'page':
	?> 	
		<div style="border: 1px solid rgb(208, 239, 251); padding: 15px; margin-top: 25px;clear: both;">
				<div class="view-field view-data-created">
				  <?php print $created?>
				</div>
				<h3><?php print $title?></h3>
				<table>
					<tr valign="top">
						<td>
							<?php if ($field_image_fid): ?>
							<div class="thumbnail">
								<img src="<?php print extract_src($field_image_fid)?>"/>
							</div>
							<?php endif; ?>				
						</td>
						<td>
							<div style="font-size: 12px;">
							  <?php print html_entity_decode($field_summary_value);?> 
							   <b> <?php print l('Read more &raquo;', "node/$node->nid", array(), null, null, false, true); ?></b>
							</div>					
						</td>
					</tr>
				</table>
		</div>
	<?php 		
 	break;
 	/*****************************************
 	 * BLOCK VIEW
 	 *****************************************/
 	case 'block':
	?> 	

		<div style="margin-top: 15px; font-size: 9px;">
		  <?php print $created?>
		</div>

		<div class="view-field view-data-title" >
		 <b> <?php print l($title, "node/$node->nid", array('style' => 'font-size: 11px;'), null, null, false, true); ?></b>
		</div>
	
	<?php 	 		
 	break;
 	
 	default:
 	break;
 }
  
 ?>
  


