<?php
// $Id$

/**
 * Implementation of hook_emfield_providers()
 * 
 * Insert Slideshare in the emvideo list of providers.
 *
 */
function slideshare_emfield_providers() {
	$files = drupal_system_listing("\.inc", drupal_get_path('module', 'slideshare') ."/providers", 'name', 0);
  return 	$files;
}

/**
 * Implementation of hok_theme()
 *
 * @param  $existing
 * @param  $type
 * @param  $theme
 * @param  $path
 */
function slideshare_theme($existing = array(), $type = null, $theme = null, $path = null) {
  $themes = array(
    'slideshare_flash' => array(
        'arguments' => array(
          'embed' => NULL,
          'width' => NULL,
          'height' => NULL,
          'field' => NULL,
          'item' => NULL,
          'node' => NULL,
          'autoplay' => NULL,
        ),
        'file' => 'slideshare.theme.inc',
    )
  );
  return $themes;
}
?>