<?php

/**
 * Provides a non-configurable action to check for default password 
 * combinations (admin/admin and editor/editor)
 *
 * TODO: add rules integration
 * TODO: make the action configurable
 * TODO: release on drupal.org
 * 
 * @author Peter Vanhee
 */

/**
* Implementation of hook_action_info().
*/
function ya_password_check_action_info() {
  return array(
    'ya_password_check_check_default_user_password_action' => array(
		'description' => t('Check for default user password combinations (admin/admin and editor/editor)'),
		'type' => 'user',
      	'configurable' => FALSE,
      	'hooks' => array(
        	'any' => TRUE
		))
  );
}

/**
* Implementation of a Drupal action.
* Checks default user password combinations and returns a warning
*/
function ya_password_check_check_default_user_password_action(&$object, $context = array()) {
	/**
	 * hardcoded default password combinations
	 */
	$settings = array(
		array('name' => 'admin', 'pass' => 'admin'),
		array('name' => 'editor', 'pass' => 'editor')
	);	
	
	global $user;
	
	foreach($settings as $setting) {
		if($user && $user->name == $setting['name'] && $user->pass == md5($setting['pass'])) {
			$message = "This account is protected with the default password '".$setting['pass']."'. ";
			$message .= "To protect your site, we strongly advise you to ".l("change your password", "user/".$user->uid."/edit").".";

			drupal_set_message($message, 'warning');
		}
	}
}

?>
