<?php
// $Id: birthdays.module,v 1.2.2.24 2007/09/18 11:21:45 maartenvg Exp $
/**
* @file The Birthdays module allows users to add their birthday to their
*       profile. It lists birthdays on a seperate page and in different
*       blocks. Users can receive an e-mail on their birthday automatically,
*       and the administrator can receive daily reminders of who are having
*       their birthday. Requires Profile Module.
*/

/**
* @TODO - Fire events
* @TODO - Add postcards
* @TODO - Make visible to VIEWS module
* @TODO - PGSQL patch
* @TODO - Regulate visibility of birthdays, birthday blocks, etc by means of the settings of the profile field
* @TODO - Make optional size & frequency: Once a week (on first day of week) == 7 days in advance or Every day == only today
* @TODO - Make POT file(s)
* @TODO - Proper DOCSYS commenting of functions
*/


/**
* Implementation of hook_help().
*/
function birthdays_help($section = '') {
  $output = '';
  switch ($section) {
    case 'admin/help#birthdays':
      $output  = t(
        "Allows users to store their birthdays and displays blocks of upcoming birthdays. Sends out e-mail on user's birthday automatically as cron job. Also sends admin reminder e-mails of upcoming user's birthdays. Most functionality is configurable in the admin settings and user settings. Requires profile.module and a present date field dedicated to the birthdays."
      );
      break;
  }

  return $output;
}

/**
* Implementation of hook_menu().
*/
function birthdays_menu($may_cache) {
  $items = array();
  if ($may_cache) {
    $items[] = array(
      'path' => 'admin/settings/birthdays',
      'title' => t('Birthdays'),
      'description' => t('Set user birthday mail and toggle user mail, upcoming birthdays mail and more.'),
      'callback' => 'drupal_get_form',
      'callback arguments' => array('birthdays_admin_settings'),
      'access' => user_access('administer site configuration'),
      'type' => MENU_NORMAL_ITEM,
    );

    $items[] = array('path' => 'admin/settings/birthdays/settings',
      'title' => t('Settings'),
      'callback' => 'drupal_get_form',
      'callback arguments' => array('birthdays_admin_settings'),
      'access' => user_access('administer site configuration'),
      'type' => MENU_DEFAULT_LOCAL_TASK,
    );

    $items[] = array(
      'path' => 'admin/settings/birthdays/sync',
      'title' => t('Synchronize'),
      'description' => t('Synchronize birthdays information of Profile module and Birthdays module. Used either when updating to a newer version of Birthdays or when integrating with an existing Profile Field.'),
      'callback' => 'birthdays_sync_page',
      'access' => user_access('administer site configuration'),
      'type' => MENU_LOCAL_TASK,
    );

    $items[] = array(
      'path' => 'birthdays',
      'title' => t('Birthdays'),
      'description' => t('List the birthdays of all users.'),
      'callback' => 'birthdays_view_page',
      'access' => user_access('access birthdays'),
      'type' => MENU_SUGGESTED_ITEM,
    );
  }

  // Set warning/error message on all pages when the birthdays profile field hasn't been set yet.
  if (!$may_cache && !variable_get('birthdays_field_name', '')) {
    drupal_set_message(t('Birthday profile field is not set. Please visit the <a href="@birthdays-settings">birthdays settings page</a>.', array('@birthdays-settings' => url('admin/settings/birthdays'))), 'error');
  }

  return $items;
}

/**
* @desc Callback for birthdays synchronisation system.
*/
function birthdays_sync_page() {
  if (variable_get('birthdays_field_name', '')) {
    return drupal_get_form('birthdays_sync_form');
  }
  else {
    return t("You haven't set a Profile field yet in the birthdays settings, please do so first before synchronising data fields.");
  }
}

/**
* Implementation of hook_form().
*/
function birthdays_sync_form() {
  $form['profile_fieldset'] = array('#type' => 'fieldset');
  $form['profile_fieldset']['description'] = array('#type' => 'item', '#title' => 'Profile to Birthdays', '#value' => t('Fill the Birthdays module\'s table with data from the Profile module\'s table. This is needed when you (re-)installed the Birthdays module, but already collected birthdays with the Profile module (e.g. for age verification).'));
  $form['profile_fieldset']['submit'] = array('#type' => 'submit', '#value' => t('Copy Profile data to Birthdays module'));

  $form['birthdays_fieldset'] = array('#type' => 'fieldset');
  $form['birthdays_fieldset']['description'] = array('#type' => 'item', '#title' => 'Birthdays to Profile', '#value' => t('Fill the Profile module\'s table with data from the Birthdays module\'s table. You can use this to copy the old data collected by a previous version of the Birthdays module after an update. It is only necessary when updating from a version of the Birthdays module which didn\'t use the Profile module.'));
  $form['birthdays_fieldset']['submit'] = array('#type' => 'submit', '#value' => t('Copy Birthdays data to Profile module'));
  return $form;
}

/**
* Implementation of hook_form_submit().
*/
function birthdays_sync_form_submit($form_id, $values) {
  if ($values['op'] == t('Copy Profile data to Birthdays module')) {
    $field = variable_get('birthdays_field_name', '');
    $result = db_query('SELECT uid FROM {users}');
    while ($user = db_fetch_object($result)) {
      $account = user_load(array('uid' => $user->uid));
      if ($account->$field) {
        user_save($account, array($field => $account->$field));
      }
    }
  }
  else {
    $field = variable_get('birthdays_field_name', '');
    $result = db_query('SELECT {dob}.uid, MONTH({dob}.birthday) AS month, YEAR({dob}.birthday) AS year, DAYOFMONTH({dob}.birthday) AS day FROM {dob}');
    while ($birthday = db_fetch_object($result)) {
      $account = user_load(array('uid' => $birthday->uid));
      $dob = array(
        'day' => $birthday->day,
        'month' => $birthday->month,
        'year' => $birthday->year
      );
      user_save($account, array($field => $dob));
    }
  }
  drupal_set_message(t('Modules have been synchronized.'));
}

/**
* @desc Callback for birthdays menu item to show a page which lists all users.
* @return Themed birthday listing of all users
*/
function birthdays_view_page() {
  // Nothing to see when the birthdays profile field hasn't been set yet.
  if (!variable_get('birthdays_field_name', '')) {
    return null;
  }
  drupal_add_css(drupal_get_path('module', 'birthdays') .'/birthdays.css');
  if (isset($_REQUEST['birthdays_filter_month'])) {
    $filter_month = (int) $_REQUEST['birthdays_filter_month'];
  }
  if (isset($_REQUEST['birthdays_filter_year'])) {
    $filter_year = (int) $_REQUEST['birthdays_filter_year'];
  }
  $output = '';
  $filter = '';
  // Right join = filtering out
  $join = variable_get('birthdays_page_settings', 0) != 2 || !empty($filter_month) || !empty($filter_year) ? 'RIGHT JOIN' : 'LEFT JOIN';
  $sort = variable_get('birthdays_page_settings', 0) == 0 || !empty($filter_month) || !empty($filter_year) ? 'MONTH({dob}.birthday), DAYOFMONTH({dob}.birthday), YEAR({dob}.birthday), ' : '';
  $filter .= !empty($filter_month) ? " AND MONTH({dob}.birthday) = ". $filter_month : '';
  $filter .= !empty($filter_year) ? " AND YEAR({dob}.birthday) = ". $filter_year : '';

  // Select all users (but ignore blocked and never logged in ones)
  $result = pager_query("SELECT {users}.uid FROM {users} ". $join ." {dob} ON {users}.uid = {dob}.uid  WHERE {users}.status <> 0 AND {users}.access <> 0". $filter ." ORDER BY ". $sort ."{users}.name", variable_get('birthdays_page_list_number', 25));

  while ($user = db_fetch_object($result)) {
    // load the user objects
    $u = user_load(array('uid' => $user->uid));
    if (empty($filter_year) || !$u->birthdays_user_hide_year) {
      $accounts[] = $u;
    }
  }

  // Call theme_birthdays_page
  $output .= theme('birthdays_page', $accounts, $filter_month, $filter_year);
  // Get the filter form

  return $output;
}

function birthdays_page_filter($filter_month = null, $filter_year = null) {
  $options_months[0] = '';
  for ($i = 1; $i <= 12; $i++) {
     $options_months[$i] = format_date(gmmktime(0, 0, 0, $i, 2, 1970), 'custom', 'F', 0);
  }

  $options_years[0] = '';
  $options_years = $options_years + drupal_map_assoc(range(1900,2050));

  $form['#prefix'] = '<div class="container-inline birthdays-filter">';
  $form['#suffix'] = "</div>";

  $form['birthdays_filter_month'] = array(
    '#type' => 'select',
    '#options' => $options_months,
    '#default_value' => $filter_month,
    '#title' => t('Filter by month'),
    '#attributes' => array('onchange' => 'submit()'),
  );

  if (variable_get('birthdays_hide_year',0) != 1) {
    $form['birthdays_filter_year'] = array(
      '#type' => 'select',
      '#options' => $options_years,
      '#default_value' => $filter_year,
      '#title' => t('Year'),
      '#attributes' => array('onchange' => 'submit()'),
    );
  }

  $form['button'] = array(
    '#type' => 'button',
    '#value' => 'Filter',
  );

  return $form;
}

function birthdays_map_month_long($month) {
  return format_date(gmmktime(0, 0, 0, $month, 2, 1970), 'custom', 'M', 0);
}

/**
* @desc Theme a birthdays page
* @var $accounts array of loaded user objects
*/
function theme_birthdays_page($accounts = array(), $filter_month, $filter_year) {
  $field = variable_get('birthdays_field_name', '');

  // $header contains the column headers
  $header = array(t('User'), t('Birthday'));

  if (variable_get('birthdays_hide_year', 0) != 1) {
    $header[] = t('Age');
  }

  if (variable_get('birthdays_show_starsign', 0)) {
    $header[] = t('Starsign');
  }

  if (variable_get('user_pictures', false)) {
    $header[] = '&nbsp;';
  }

  // $rows contains all cells
  $rows = array();
  $i = 0;
  // For each user
  foreach ($accounts as $account) {
    //Theme username (with link and such) and format date field.
    $rows[$i] = array(theme('username', $account), _birthdays_show_date($account->$field, $account));

    $age = _birthdays_show_age($account);
    $rows[$i][] = isset($age) ? $age : '';

    if (variable_get('birthdays_show_starsign', 0)) {
      $rows[$i][] = birthdays_get_starsign_image($account->birthdays_starsign, variable_get('birthdays_show_starsign', 0));
    }

    if (variable_get('user_pictures', false)) {
      $rows[$i][] = theme_user_picture($account);
    }

    $i++;
  }

  // Return a table. Everthing else (titles, and such) is handled by the page system.
  if (variable_get('birthdays_page_show_filters', 1)) {
    $str .= drupal_get_form('birthdays_page_filter', $filter_month, $filter_year);
  }
  $str .= theme('table', $header, $rows);
  $str .= theme('pager', NULL, variable_get('birthdays_page_list_number', 25), 0);

  return $str;
}

/**
* Implementation of hook_form().
*/
function birthdays_admin_settings() {

  $form['birthdays_show_starsign'] = array(
    '#type' => 'select',
    '#title' => t('Show star signs'),
    '#default_value' => variable_get('birthdays_show_starsign', 0),
    '#options' => array(
      0 => t('No'),
      1 => t('Yes, with link to Yahoo Astrology'),
      2 => t('Yes, without link to Yahoo Astrology')
    ),
    '#description' => t('Select whether the star signs should be enabled.'),
  );


  // Get fields from the profile.module of the type 'date'.
  $options = _birthdays_get_date_fields();
  // If there aren't any 'date' fields, throw a warning
  if (empty($options)) {
    drupal_set_message(t('No profile fields of type \'date\' were found, please <a href="@profile-settings-page">create one here</a>.', array('@profile-settings-page' => url('admin/user/profile/add/date'))), 'error');
  }

  $form['birthdays_field_name'] = array(
    '#type' => 'select',
    '#title' => t('Profile field'),
    '#default_value' => variable_get('birthdays_field_name', ''),
    '#description' => t('Choose the profile field of type \'date\' you want to use as date of birth.'),
    '#options' => $options,
    '#required' => TRUE,
  );


  $form['birthdays_hide_year'] = array(
    '#type' => 'select',
    '#title' => t('Hide year and age'),
    '#default_value' => variable_get('birthdays_hide_year', 0),
    '#description' => t('Select whether the birth year and age should be shown.'),
    '#options' => array(
      0 => t('No'),
      1 => t('Yes'),
      2 => t('User optional, \'No\' by default'),
    ),
  );

  $form['birthdays_page'] = array(
    '#type' => 'fieldset',
    '#title' => t('Birthdays page settings'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );
  $form['birthdays_page']['birthdays_page_settings'] = array(
    '#type' => 'select',
    '#title' => t('Set birthdays page settings'),
    '#default_value' => variable_get('birthdays_page_settings', 0),
    '#description' => t('Select whether users that haven\'t entered their date of birth should be shown on the birthdays page, and whether the list should be ordered by birthday or by username.'),
    '#options' => array(
      0 => t('Filter users, sort by date'),
      1 => t('Filter users, sort by username'),
      2 => t('Do not filter users, sort by username'),
    ),
  );

  $form['birthdays_page']['birthdays_page_list_number'] = array(
    '#type' => 'textfield',
    '#title' => t('Birthdays page size'),
    '#default_value' => variable_get('birthdays_page_list_number', 25),
    '#description' => t('How many users should be listed on each page on the Birthdays listing?'),
    '#required' => TRUE,
  );

  $form['birthdays_page']['birthdays_page_show_filters'] = array(
    '#type' => 'select',
    '#title' => t('Show filter options'),
    '#default_value' => variable_get('birthdays_page_show_filters', 1),
    '#description' => t('Show the "Filter by month and year" selections on the birthdays page. When "Hide year" has been set to "Yes", the year filter isn\'t shown.'),
    '#options' => array(
      0 => t('No'),
      1 => t('Yes'),
    ),
  );

  $form['birthdays_remind'] = array(
    '#type' => 'radios',
    '#title' => t('Send upcoming birthdays to admin'),
    '#default_value' => variable_get('birthdays_remind', 0),
    '#options' => array(1 => t('Yes'), 0 => t('No')),
    '#description' => t('Do you want a daily e-mail containing all upcoming birthdays (for the next week)?')
  );

  // Fieldset for User E-mails
  $form['birthdays_email'] = array(
    '#type' => 'fieldset',
    '#title' => t('E-mail user'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );

  $form['birthdays_email']['birthdays_send_user'] = array(
    '#type' => 'select',
    '#title' => t('Send user e-mail on day of birth'),
    '#default_value' => variable_get('birthdays_send_user', 0),
    '#options' => array(
      0 => t('No'),
      1 => t('Yes'),
      2 => t('User optional, \'Yes\' by default'),
    ),
    '#description' => t('Should users that have their birthday today receive an e-mail?'),
  );

  $form['birthdays_email']['birthdays_send_user_subject'] = array(
    '#type' => 'textfield',
    '#title' => t('Subject'),
    '#default_value' => variable_get('birthdays_send_user_subject', t('Happy Birthday!')),
  );

  $form['birthdays_email']['birthdays_send_user_message'] = array(
    '#type' => 'textarea',
    '#title' => t('Message'),
    '#default_value' => variable_get('birthdays_send_user_message', t("Hey @name,
Happy birthday!
Hope you have a great day!")
    ),
    '#description' => t('@name will be replaced by the username.'),
  );


  return system_settings_form($form);
}

function birthdays_admin_settings_submit($form_id, $values) {
  $field = _birthdays_get_field($values['birthdays_field_name']);
  $op = isset($form_values['op']) ? $form_values['op'] : '';
  if ($op == t('Reset to defaults')) {
    variable_del('birthdays_field_id');
  }
  else {
    variable_set('birthdays_field_id', $field->fid);
  }

  return system_settings_form_submit($form_id, $values);
}


/**
* Implementation of hook_perm().
*/
function birthdays_perm() {
  return array('access birthdays', 'delete birthday');
}

/**
* Implementation of hook_cron().
*/
function birthdays_cron() {
  // Either user mail or admin mail is activated and when the birthdays profile field has been set.
  if (variable_get('birthdays_field_name', '') != '' && (variable_get('birthdays_send_user', 0) || variable_get('birthdays_remind', 0))) {
    // Perform these actions just once per day
    if (variable_get('birthdays_last_cron', 0) < (time() - 3600*24)) {
      _birthdays_send_user_message();
      _birthdays_send_admin_message();
      // Reset time limit
      variable_set('birthdays_last_cron', time());
    }
  }
}

/**
* Implementation of hook_block
*/
function birthdays_block($op = 'list', $delta = 'by_days', $edit = array()) {
  switch ($op) {
    // List the blocks on the blocks settings page
    case 'list':
      $blocks['by_days']['info'] = t('Birthdays Block: Next N days');
      $blocks['by_birthdays']['info'] = t('Birthdays Block: N upcoming birthdays');
      return $blocks;

    // Configure the blocks
    case 'configure':
      switch ($delta) {
        case 'by_days':
          $form["birthdays_block_settings"] = array(
            '#type' => 'textfield',
            '#title' => t("Number of days to show"),
            '#default_value' => variable_get("birthdays_block_number_by_days", 7),
            '#size' => 2,
            '#maxlength' => 2,
            '#description' => t("Number of days looking forward for upcoming birthdays. Use 1 for today's birthdays only. Note: it might show more or less birthday items than the specified number of days, because not all days have birthdays, and some days have multiple birthdays."),
            '#required' => true,
          );
          return $form;

        case 'by_birthdays':
          $form["birthdays_block_settings"] = array(
            '#type' => 'textfield',
            '#title' => t("Number of birthdays to show"),
            '#default_value' => variable_get("birthdays_block_number_by_birthdays", 6),
            '#size' => 2,
            '#maxlength' => 2,
            '#description' => t("Number of upcoming birthdays to list in the block. It will show exactly the specified number of birthdays, even if more people have their birthday on the same day. In that case, there will be people who will never be shown."),
            '#required' => true,
          );
          return $form;
      }

    // Save the block's configuration
    case 'save':
      variable_set('birthdays_block_number_'. $delta, $edit['birthdays_block_settings'] );
      return;

    // View a block
    case 'view':
      // Nothing to show when birthday_field_name is still empty
      // Don't show anything when the current user doesn't have the rights.
      if (variable_get('birthdays_field_name', '') != '' && user_access('access birthdays')) {
        switch ($delta) {
          case 'by_days':
            // Get birthdays
            $amount = variable_get("birthdays_block_number_by_days", 7);
            // Theme block
            $block['content'] = theme('birthdays_block', birthdays_get_birthdays_by_days($amount), $amount, $delta);
            break;
          case 'by_birthdays':
            // Get birthdays
            $amount = variable_get("birthdays_block_number_by_birthdays", 6);
            // Theme block
            $block['content'] = theme('birthdays_block', birthdays_get_birthdays($amount), $amount, $delta);
            break;
        }
        $block['subject'] = t('Upcoming Birthdays');

        return $block;
      }
  }
}

/**
*  @desc Helper function for displaying only todays birthdays
*  @return An array containing all user objects that have their birthday today
*/
function birthdays_get_todays_birthdays() {
  return birthdays_get_birthdays_by_days(1);
}

/**
* @desc Get all birthdays of the upcomming X days
* @var Integer stating the amount of days to look forward, including today.
* @return An array containing user objects meeting the criteria
*/
function birthdays_get_birthdays_by_days($amount) {
  $birthdays = array();
  // Current user, needed for timezone information
  global $user;

  // $amount should be larger or equal to 1
  if ($amount < 1) {
    $amount = 1;
  }

  // Get user time zone
  // needed to determine what day 'today' is in the timezone of the user/website.
  if (variable_get('configurable_timezones', 1) && $user->uid && strlen($user->timezone)) {
    $timezone = $user->timezone;
  }
  else { // else use timezone of Drupal installation
    $timezone = variable_get('date_default_timezone', 0);
  }

  // MySQL prior to 4.1.1 has no option to use UTC, while drupal uses UTC.
  // This is compensated by subtracting the machines timezone from the Drupal timezone.
  // I believe the assumption is that the HTTP-server has the same timezone as the MySQL server.
  $timezone -= date('Z');

  // Hack to look further than the end of the year, if needed.
  $current_year = date('Y');
  $next_year = $current_year + 1;

  /* Query:
    - All dates are compensated for the timezone. This makes sure that someone in Asia will see the birthdays
      of day 2 while someone in America still sees day 1.
    - Blocked users are not shown
    - Users that haven't logged in yet are also not shown (Drupal prohibits accessing their profile, thus showing
      a link to the profile is unwanted). This is a anti spammers method.
    - First part selects all birthdays that are in the next year when the interval exceeds the end of this year.
    - Second part selects all birthdays that are between the begin and end date and are in the current year
    */
  $result = db_query(
    "SELECT {dob}.uid FROM {dob}, {users} WHERE {users}.uid = {dob}.uid AND {users}.status <> 0 AND {users}.access <> 0
    AND (
    (
      DATE_FORMAT({dob}.birthday,'$next_year%%m%%d') - DATE_FORMAT(ADDDATE(ADDDATE(NOW(),INTERVAL %d SECOND),INTERVAL %d DAY),'%%Y%%m%%d') < 0
    )
    OR
    (
      DATE_FORMAT({dob}.birthday,'$current_year%%m%%d') - DATE_FORMAT(ADDDATE(NOW(),INTERVAL %d SECOND),'%%Y%%m%%d') >= 0
      AND
      DATE_FORMAT({dob}.birthday,'$current_year%%m%%d') - DATE_FORMAT(ADDDATE(ADDDATE(NOW(),INTERVAL %d SECOND),INTERVAL %d DAY),'%%Y%%m%%d') < 0
    ) )
    ORDER BY MONTH({dob}.birthday), DAYOFMONTH({dob}.birthday), YEAR({dob}.birthday), {users}.name", $timezone, $amount, $timezone, $timezone, $amount
  );


  while ($account = db_fetch_object($result)) {
    $birthdays[] = $account->uid;
  }

  // Return array of uids that have their birthday
  return $birthdays;
}


/**
* @desc Get the next X birthdays
* @var Integer stating the amount of birthdays to retrieve.
* @return An array containing user objects meeting the criteria
*/
function birthdays_get_birthdays($amount) {
  $birthdays = array();

  // Current Logged in user
  global $user;

  // Get user time zone
  // needed to determine what day 'today' is in the timezone of the user/website.
  if (variable_get('configurable_timezones', 1) && $user->uid && strlen($user->timezone)) {
    $timezone = $user->timezone;
  }
  else {
    $timezone = variable_get('date_default_timezone', 0);
  }

  // $amount should be larger or equal to 1
  if ($amount < 1) {
    $amount = 1;
  }

  // MySQL prior to 4.1.1 has no option to use UTC, while drupal uses UTC.
  // This is compensated by subtracting the machines timezone from the Drupal timezone.
  // I believe the assumption is that the HTTP-server has the same timezone as the MySQL server.
  $timezone -= date('Z');

  /* Query:
    - Select all active users that have their birthday today or in the future (stops at 31-12)
    - return at most $amount users
    - Don't show blocked users
    - Users that haven't logged in yet are also not shown (Drupal prohibits accessing their profile, thus showing
      a link to the profile is unwanted). This is a anti spammers method.
  */
  $result = db_query_range(
    "SELECT {dob}.uid FROM {dob}, {users} WHERE {users}.uid = {dob}.uid AND {users}.status <> 0 AND {users}.access <> 0
    AND DATE_FORMAT({dob}.birthday,'%%c%%d') - DATE_FORMAT(ADDDATE(NOW(),INTERVAL %d SECOND),'%%c%%d') >= 0
    ORDER BY MONTH({dob}.birthday), DAYOFMONTH({dob}.birthday), YEAR({dob}.birthday), {users}.name", $timezone, 0, $amount
  );

  while ($account = db_fetch_object($result)) {
    $birthdays[] = $account->uid;
  }

  // If less than $amount results returned, look for more after 31-12
  // return at most the difference between the number already found and
  if (db_num_rows($result) < $amount) {
    $result = db_query_range(
      "SELECT {dob}.uid FROM {dob}, {users} WHERE {users}.uid = {dob}.uid AND {users}.status <> 0 AND {users}.access <> 0
      AND DATE_FORMAT({dob}.birthday,'%%c%%d') - DATE_FORMAT(ADDDATE(NOW(),INTERVAL %d SECOND),'%%c%%d') < 0
      ORDER BY MONTH({dob}.birthday), DAYOFMONTH({dob}.birthday), YEAR({dob}.birthday), {users}.name", $timezone, 0, $amount - db_num_rows($result)
    );

    while ($account = db_fetch_object($result)) {
      $birthdays[] = $account->uid;
    }
  }

  // Return array of uids that have their birthday
  return $birthdays;
}

/**
* @desc Theme function of the blocks
* @returns themed content
*/
function theme_birthdays_block($birthdays, $amount, $delta) {
  $str = '<table>';
  $field = variable_get('birthdays_field_name', '');
  if (!empty( $birthdays)) {
    foreach ($birthdays as $b) {
      $user = user_load(array('uid' => $b));
      $age = _birthdays_show_age($user);
      // +1 when the birthday isn't today, because it shows the age the person will be on his/her birthday
      $age = isset($age) ? '('. ($user->age + ($user->{$field}['day'] != format_date(time(), 'custom', 'd'))) .')' : '';

      $user->{$field}['year'] = NULL; // Don't show the year in blocks
      $str .= '<tr><td>'. theme('username', $user) .'&nbsp;<small>'. $age .'</small></td><td>'. _birthdays_show_date($user->{$field}, $user) .'</td></tr>';
    }
  }
  else {
    $str = t('Nobody is having their birthday soon.');
  }

  $str .= '</table>
<ul><li class="leaf">'. l(t('More...'), 'birthdays') .'</li></ul>';

  return $str;
}


/**
* Implementation of hook_user().
*/
function birthdays_user($op, &$edit, &$user, $category = NULL) {
  // Do nothing with user when birthdays_field_name is not yet set
  if (!variable_get('birthdays_field_name', '')) {
    return;
  }

  switch ($op) {
    case 'load':
      return birthdays_load_user($user);
    case 'update':
    case 'insert':
      return birthdays_save_user($edit, $user, $category);
    case 'form':
      return birthdays_form_user($edit, $user, $category);
    case 'register':
      return birthdays_form_user($edit, $user, $category, TRUE);
    case 'delete':
      // Delete from {dob} table, other information is handled by profile.module and user.module
      db_query('DELETE FROM {dob} WHERE uid = %d', $user->uid);
  }
}

/**
* @desc Inject information on a user load
*/
function birthdays_load_user(&$user) {
  // Pre-load birthday-information into $user
  profile_load_profile($user);

  // Get the name of the profile field used
  $field = variable_get('birthdays_field_name', '');

  // If it was set by the user
  if ($user->$field) {
    // Set the user's age
    $user->age = _birthdays_calculate_age($user->$field);
  }
}

/**
* @desc Inject information and save birthday when editing or adding a user
*/
function birthdays_save_user(&$edit, &$user, $category) {
  // Duplicate birthday-information in separate table for easy searching

  // Get the name of the profile field used
  $field = variable_get('birthdays_field_name', '');

  // Only continue when the field is present in the form results
  if (!empty($field) && array_key_exists($field, $edit)) {
    // Extract the date information
    extract($edit[$field]);
    // Set the starsign for the user.module to save in the {users}.data field
    $edit['birthdays_starsign'] = _birthdays_get_starsign($day, $month);

    if ($day && $year && $month) {
      // Delete the old
      db_query("DELETE FROM {dob} where uid = %d", $user->uid);
      // Insert the new
      db_query("INSERT INTO {dob} (uid, birthday) VALUES (%d, '%d-%d-%d');", $user->uid, $year, $month, $day);
    }
  }
}

/**
* @desc Alter the way the birthday is shown. This is fired after every module has filled the profile.
*/
function birthdays_profile_alter(&$user, &$fields) {
  // If the birthdays_field_name hasn't been set yet, do not continue
  if (!variable_get('birthdays_field_name', '')) {
    return;
  }

  // Get the entire field information of the birthdays date field
  $field = _birthdays_get_field(variable_get('birthdays_field_name', ''));

  // If the field existed, and is amongst the profile fields to be shown, it is save to continue
  if (!empty( $field ) && array_key_exists($field->category, $fields) && array_key_exists($field->name, $fields[$field->category])) {

    // Do you have access to see birthdays?
    if (user_access('access birthdays')) {
      // Show starsign (will be hidden when needed)
      $starsign = '<span class="birthdays-starsign">'.
        birthdays_get_starsign_image($user->birthdays_starsign, variable_get('birthdays_show_starsign', 0 )) .
        '</span>&nbsp;&nbsp;&nbsp;';

      // Show age (when allowed by user and administrator)
      if (variable_get('birthdays_hide_year', 0) == 0 || (variable_get('birthdays_hide_year', 0) == 2 && $user->birthdays_user_hide_year == 0)) {
        $age = '&nbsp;&nbsp;&nbsp;<span class="birthdays-age">('. $user->age .')</span>';
      }

      // Alter the profile field setup by profile.module. Show medium format in stead of short format
      $fields[$field->category][$field->name]['value'] = $starsign . _birthdays_show_date($user->{$field->name}, $user, 'medium') . $age ;

    }
    else {
      // No access? Remove from profile to show
      unset($fields[$field->category][$field->name]);
    }
  }
}

/**
* @desc Adds user options to the profile form which are saved in {users}.data and
*       are loaded during a user_load().
* @return fields for the form
*/
function birthdays_form_user($edit, $user, $category, $register = FALSE) {
  // Get entire profile field object
  $field = _birthdays_get_field(variable_get('birthdays_field_name', ''));

  // If the Delete Birthday button was pressed: delete the birthday
  $op = isset($edit['op']) ? $edit['op'] : '';
  if ($op == t('Reset Birthday')) {
    db_query("DELETE FROM {dob} where uid = %d", $user->uid);

    $edit = array();
    $edit['birthdays_starsign'] = '';
    $edit[$field->name] = '';

    user_save($user, $edit, $field->category);

    return 'user/'. $user->uid;
  }


  // If the called category is the category of the form field
  if ($category == $field->category || ($field->register && $register)) {
    // If the hiding of the year is a user option: show the option
    if (variable_get('birthdays_hide_year', 0) == 2) {
      $form[$field->category]['birthdays_user_hide_year'] = array(
        '#type' => 'checkbox',
        '#title' => t("Hide age and birth year"),
        '#default_value' => (int) $user->birthdays_user_hide_year,
        '#description' => t("Do not show your age and your year of birth."),
        '#return_value' => 1,
        '#weight' => $field->weight + 1
      );
    }

    // If the birthday user mail is optionally, show the option
    if (variable_get('birthdays_send_user', 0) == 2) {
      $form[$field->category]['birthdays_user_send_mail'] = array(
        '#type' => 'checkbox',
        '#title' => t("Do not send birthday mail"),
        '#default_value' => (int) $user->birthdays_user_send_mail,
        '#description' => t("Do not send me an e-mail or e-card when it's my birthday."),
        '#return_value' => 1,
        '#weight' => $field->weight + 1
      );
    }

    if (user_access('delete birthday') && !$register) {
      $form[$field->category]['submit'] = array(
        '#type' => 'button',
        '#value' => t("Reset Birthday"),
        '#weight' => $field->weight + 1,
      );
    }
  }
  return $form;
}

/**
* @desc Sends e-mail to administrator once a day as reminder about the upcoming 7 days
* @todo Add frequency options (once a day, every week, monthly)
*/
function _birthdays_send_admin_message() {
  // Only proceed when admin messages are enabled
  if (variable_get('birthdays_remind', 0)) {
    // Get birthdays
    $users = birthdays_get_birthdays_by_days(7);
    // Set message
    $message = t("In the next %number days, the following users are having their birthdays:", array('%number' => 7));

    $field = variable_get('birthdays_field_name', '');
    // Build list of users
    foreach ($users as $user) {
      $account = user_load(array('uid' => $user));
      $message .= "\n". $account->name .' at '. $account->{$field}['day'] .'/'. $account->{$field}['month'];
    }

    // If there were any users:
    if (count($users) > 0) {
      // Get site e-mail to send reminder to and from
      $from = variable_get('site_mail', ini_get('sendmail_from'));
      $to = $from;
      $subject = t("Upcoming Birthdays");

      // Send the mail
      drupal_mail('birthdays_admin_mail', $to, $subject, $message, $from);
      // Log action
      watchdog('Birthdays', t('Sent birthday overview e-mail to admin'), WATCHDOG_NOTICE, '&#160;');
    }
  }
}

/**
* @desc Send all birthdays on this day a message
* @todo re-introduce the postcard module to make it fun
*/
function _birthdays_send_user_message() {
  // If messaging is enabled
  if (variable_get('birthdays_send_user', 0) > 0) {
    // Get all users having their birthday today
    $users = birthdays_get_todays_birthdays();
    // Get site address
    $from = variable_get('site_mail', ini_get('sendmail_from'));


    $subject = variable_get('birthdays_send_user_subject', t('Happy Birthday!'));
    $message = variable_get('birthdays_send_user_message', t("Hey @name,
Happy birthday!
Hope you have a great day!"));
    foreach ($users as $user) {
      // Load user
      $account = user_load(array('uid' => $user));
      // If user and/or administrator allow sending messages
      if (variable_get('birthdays_send_user', 0) == 1 || (variable_get('birthdays_send_user', 0) == 2 && $account->birthdays_user_send_mail == 0)) {
        // Replace @name in message by username
        $parsed_message = strtr($message, array('@name' => check_plain($account->name)));

        // Send mail
        drupal_mail('birthdays_user_message', $account->name .'<'. $account->mail .'>', $subject, $parsed_message, $from);
        // Log actions
        watchdog('Birthdays', t('Sent @name a birthday e-mail', array('@name'=> $account->name)), WATCHDOG_NOTICE, '&#160;');
      }
    }
  }
}

/**
* @desc Get starsign based on date of birth
* @var $day and $month, decribing date of birth
* @return The name of the starsign
*/
function _birthdays_get_starsign($day, $month) {

  switch ($month) {
    case 1:
      $starsign = $day < 20 ? 'capricorn' : 'aquarius';
      break;
    case 2:
      $starsign = $day < 20 ? 'aquarius' : 'pisces';
      break;
    case 3:
      $starsign = $day < 21 ? 'pisces' : 'aries';
      break;
    case 4:
      $starsign = $day < 20 ? 'aries' : 'taurus';
      break;
    case 5:
      $starsign = $day < 21 ? 'taurus' : 'gemini';
      break;
    case 6:
      $starsign = $day < 22 ? 'gemini' : 'cancer';
      break;
    case 7:
      $starsign = $day < 23 ? 'cancer' : 'leo';
      break;
    case 8:
      $starsign = $day < 23 ? 'leo' : 'virgo';
      break;
    case 9:
      $starsign = $day < 23 ? 'virgo' : 'libra';
      break;
    case 10:
      $starsign = $day < 23 ? 'libra' : 'scorpio';
      break;
    case 11:
      $starsign = $day < 22 ? 'scorpio' : 'sagitarius';
      break;
    case 12:
      $starsign = $day < 22 ? 'sagitarius' : 'capricorn';
      break;
  }

  return $starsign;
}

/**
* @desc Retrieve all fields of type 'date' from the profile.module's tables
* @return array with fieldnames
*/
function _birthdays_get_date_fields() {
  $options = array();
  $result = db_query("SELECT name FROM {profile_fields} WHERE type = 'date'");

  while ($field = db_fetch_object($result)) {
    $options[$field->name] = $field->name;
  }

  return $options;
}

/**
* @desc Retrieve profile field object
* @var $field: name of field to retrieve
* @return profile field object
*/
function _birthdays_get_field($field) {
  if (!empty($field)) {
    $ret = db_fetch_object(db_query("SELECT * FROM {profile_fields} WHERE name = '%s'", $field));
  }
  else {
    $ret = null;
  }

  return $ret;
}

/**
* @desc Return the picture of a starsign, given the name. Links to Yahoo! when option is selected.
*/
function birthdays_get_starsign_image($starsign, $show = 0) {
  $str = '';

  // Only show starsign when enabled
  if ($show > 0 && !empty( $starsign)) {
    // Image based on thme path.
    $str = '<img src="'. base_path() . drupal_get_path('module', 'birthdays') .'/starsigns/'. $starsign .'.gif" alt="'. t($starsign) .'" />';

    // If link should be shown: update $str
    if ($show == 1) {
      $str = '<a href="http://astrology.yahoo.com/astrology/general/dailyoverview/'. $starsign .'" target="_blank" title="'. t($starsign) .'">'. $str .'</a>';
    }
  }

  // Return HTML
  return $str;
}

function birthdays_form_alter($form_id, &$form) {
  if ($form_id == 'profile_field_form') {
    $form['#submit'] = (array)$form['#submit'] + array('birthdays_profile_form_submit' => array());
  }
}

function birthdays_profile_form_submit($form_id, $form_values) {
  if ($form_values['fid'] == variable_get('birthdays_field_id', 0)) {
    variable_set('birthdays_field_name', $form_values['name']);
  }
}

/**
* @desc Calculate age
* @var array containing fields 'year', 'month' and 'day'
* @return age
*/
function _birthdays_calculate_age($date) {
  // If date is not empty
  if (is_array( $date)) {
    // extract date
    extract($date);

    // call main age function (no overloading in PHP)
    return _birthdays_calculate_age_2($day, $month, $year);
  }
  else {
    return null;
  }
}

/**
* @desc Calculate age
* @var $year, $month, $day as expected
* @return age
*/
function _birthdays_calculate_age_2($day, $month, $year) {
  if ($year && $month && $day) {
    // age = (current year - birthyear) - 1 (when the birthday hasn't arrived yet).
    return format_date(time(), 'custom', 'Y') - $year - (format_date(time(), 'custom', 'nd') < $month . str_pad($day, 2, 0, STR_PAD_LEFT));
  }
  else {
    return null;
  }
}

function _birthdays_show_age($user) {
  $age = null;
  if (isset($user->age) && (variable_get('birthdays_hide_year', 0) == 0 || (variable_get('birthdays_hide_year', 0) == 2 && $user->birthdays_user_hide_year == 0))) {
    $age = $user->age;
  }
  return $age;
}

/**
* @desc Format date array
*/
function _birthdays_show_date($date, $user, $format = 'small') {
  if (is_array($date)) {
    // Extract date
    extract($date);

    // Call main format function
    return _birthdays_show_date_2($day, $month, $year, $user, $format);
  }
  else {
    return null;
  }
}

/**
* @desc Format date, optionally hide year
*/
function _birthdays_show_date_2($day, $month, $year, $user, $type = 'small') {
  $str = '';
  // Determine format type
  switch ($type) {
    case 'medium':
      $format = variable_get('date_format_medium', 'D, m/d/Y - H:i');
      break;
    case 'small':
    default:
      $format = variable_get('date_format_short', 'm/d/Y - H:i');
  }

  // remove time from (- H:i)
  //$format = substr($format, 0, -6);

  // If admin or user decide to hide the age&year: hide year
  if ($year && ( variable_get('birthdays_hide_year', 0) == 1 || (variable_get('birthdays_hide_year', 0) == 2 && $user->birthdays_user_hide_year == 1))) {
    $year = NULL;
  }

  // Replacement array (can't use date() because of 1970 limitations in e.g. Windows PHP4)
  $replace = array(
    'd' => sprintf('%02d', $day),
    'D' => NULL,
    'j' => $day,
    'm' => sprintf('%02d', $month),
    'M' => map_month($month),
    'Y' => $year,
    'H:i' => NULL,
    'G:i' => NULL,
    'g:ia' => NULL,
    'F' => t(gmdate('F', mktime(0, 0, 0, $month, 15, 2000))),
  );

  // Translate string to correct format
  $str .= strtr($format, $replace);
  $str = trim($str, '/ ,.:-');

  return $str;
}