<?php

/**
 * Provides a block with credits to Youth Agora
 *
 * @author Andrea Pescetti
 */

function ya_credits_block($op = 'list', $delta = 0, $edit = array()) {
  switch ($op) {
    case 'list':
      $blocks[0] = array(
        'info'       => t('Youth Agora Credits'),
      );
      return $blocks;
    case 'configure':
      $form = array();
      return $form;
    case 'save':
      return;
    case 'view': default:
      $block['subject'] = t('A Youth Agora template');
      $block['content'] = ya_credits_contents();
      return $block;
  }
}

function ya_credits_contents() {
return t("The ".variable_get('site_name','present')." website is based on
          a freely available <a href='http://www.drupal.org'>Drupal</a>
          template by <a href='http://www.youthagora.org'>Youth Agora</a>.
          <br/>
          You can <a href='http://download.youthagora.org'>download your
          template</a> now and use it for your next website!
		  <br/>
		  <a href='http://www.youthagora.org'>
		  <img
		     id='ya_logo_footer'
		     src='".base_path()."profiles/project/themes/base/images/ya_logo.png'/>
		  </a>");
}

?>
