<?php
// $Id: export.install,v 1.2.2.2 2008/11/27 23:36:36 danielb Exp $
// $Name: DRUPAL-6--1-4 $

/**
 * Implementation of hook_uninstall.
 */
function export_uninstall() {
  
  variable_del('export_method');
  variable_del('export_omitted');
  variable_del('export_nodes_without_confirm');
  $types = node_get_types('names');
  foreach ($types as $type => $name) {
    variable_del('export_reset_'. $type);
  }
}

