<?php


/**
 * Implementation of hook_init().
 */
function ya_satellite_blocks_init() {  
  drupal_add_css(drupal_get_path('module', 'ya_satellite_blocks') . '/ya_satellite_blocks.css');
}

/**
 * Provides a block with credits to Youth Agora
 */
function ya_satellite_blocks_block($op = 'list', $delta = 0, $edit = array()) {
  switch ($op) {
    case 'list':
      $blocks[0] = array('info' => t('ESN Satellite Credits') );
      $blocks[1] = array('info' => t('ESN Section info') );
      return $blocks;
    case 'configure':
      $form = array( );
      return $form;
    case 'save':
      return;
    case 'view':
    default:
      switch ($delta) {
        case 0:
          $block['subject'] = t('A Youth Agora template');
          $block['content'] = ya_satellite_blocks_contents();
          break;
        case 1:
          $block['subject'] = '';
          $block['content'] = ya_satellite_blocks_section_info();
          break;
      } 
      return $block;
  }
}

function ya_satellite_blocks_contents() {
  return t("The " . variable_get('site_name', 'present') . " website is based on
          a freely available <a href='http://www.drupal.org'>Drupal</a>
          template by <a href='http://www.youthagora.org'>Youth Agora</a>.
          <br/>
          You can <a href='http://download.youthagora.org'>download your
          template</a> now and use it for your next website!
          
          <div class=\"footer-logos-container\">
          <div class=\"footer-logo\">
            <a href='http://www.esn.org'>
              <img id='esn_logo_footer' src='" . base_path() . drupal_get_path('module', 'ya_satellite_blocks') . "/images/esn_logo.png' alt='ESN logo' />
            </a>
          </div>
          <div class=\"footer-logo\">
            <a href='http://www.youthagora.org'>
              <img id='ya_logo_footer' src='" . base_path() . drupal_get_path('module', 'ya_satellite_blocks') . "/images/ya_logo.png' alt='Youth Agora logo' />
            </a>
          </div>
          </div>
          ");
}


function ya_satellite_blocks_section_info() {
  
  $token = token_get_values('esn');
  $data = array_combine($token->tokens, $token->values);
  
  $country = strtolower($data['country.country']);
  $country = $country ? $country : 'esn';
  $section_name = $data['section.sectionname'];
  $section_info = $data['section.street'].' '.$data['section.location'].' '.$data['country.cn'];  
  
  if(user_access('view advanced help topic')) $out .= theme('advanced_help_topic', 'ya_satellite_blocks', 'about');
  $out .= '<div class="section-logo">';
  $out .= '<img id="esn_logo" src="' . base_path() . drupal_get_path('theme', 'satellite') . '/images/countries/40/'.$country.'.png" alt="logo" />';
  $out .= '</div>';
  $out .= '<div class="section-name">';
  $out .= $section_name;  
  $out .= '</div>';
  $out .= '<div class="section-info">';
  $out .= $section_info;
  $out .= '</div>';
  
  return $out;
}


// function help_example_index_page() {
//   $output = theme('advanced_help_topic', 'help_example', 'about-php');
//   $output .= '&nbsp;' . t('Click the help icon to view some example help about the PHP programming language (from wikipedia.org). Be sure to run cron to update the index if you want to try out the search features.');
//   return $output;
// }



