<?php 
/**
 * views template to output one 'row' of a view.
 * This code was generated by the views theming wizard
 * Date: Mon, 09/04/2007 - 11:57
 * View: News
 *
 * Variables available:
 * $view -- the entire view object. Important parts of this object are
 *   News, .
 * $view_type -- The type of the view. Probably 'page' or 'block' but could
 *   also be 'embed' or other string passed in from a custom view creator.
 * $node -- the raw data. This is not a real node object, but will contain
 *   the nid as well as other support fields that might be necessary.
 * $count -- the current row in the view (not TOTAL but for this page) starting
 *   from 0.
 * $stripe -- 'odd' or 'even', alternating. * $created -- Display the post time of the node.
 * $created_label -- The assigned label for $created
 * $title -- Display the title of the node.
 * $title_label -- The assigned label for $title
 * $body -- Display the Main Content.
 * $body_label -- The assigned label for $body
 *
 * This function goes in your views-list-News.tpl.php file
 */
 
 
 //now we add the stylesheet...
  drupal_add_css(path_to_theme() .'/views-list-News.css');
  
  ?>
<div class="view-label view-field-created">
  <?php print $created_label ?>
</div>
<div class="view-field view-data-created">
  <?php print $created?>
</div>

<div class="view-label view-field-title">
  <?php print $title_label ?>
</div>
<div class="view-field view-data-title">
  <?php print $title?>
</div>

<div class="view-label view-field-body">
  <?php print $body_label ?>
</div>
<div class="view-field view-data-body">
  <?php print $body?>
</div>

