<?php
// $Id: pathauto.install,v 1.1.2.2 2007/04/05 15:43:03 greggles Exp $

/**
 * @file 
 * Provides install, updated, and uninstall functions for Pathauto.
 */

/**
 * Implementation of hook_uninstall().
 */
function pathauto_uninstall() {
  // Delete all the pathauto variables and then clear the variable cache.  
  db_query("DELETE FROM {variable} WHERE name LIKE 'pathauto_%'");
  cache_clear_all('variables', 'cache');
}